// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.

export const CLIENT_TYPES_MAP: Record<string, Record<string, string>> = {};
