name: Bug Report (transform)
description: Bug report specific to a particular transform (like `v2-to-v3`)
title: "[Bug?]: "
labels: ["bug", "triage"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Fixing bugs is always a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement a fix"

  - type: dropdown
    id: template-name
    attributes:
      label: Template name
      description: Which template are you seeing this error for?
      options:
        - v2-to-v3
        - N/A (described above)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. A bug is **unintended**. A feature not being implemented is **not a bug**.
      placeholder: |
        eg: Running transform "transformName" on the provided input causes it to crash.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Input code
      description: The _minimal_ input file to reproduce your issue.
      placeholder: |
        ```ts
        import AWS from "aws-sdk";

        const region = "us-west-2";
        const client = new AWS.DynamoDB({ region });
        const response = await client.listTables({}).promise();
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed failure
      description: A concise description of what error you're experiencing.
      placeholder: |
        eg: The aws-sdk-js-codemod script returned the following error:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected output
      description: The output file you expected to see.
      placeholder: |
        ```ts
        import { DynamoDB } from "@aws-sdk/client-dynamodb";

        const region = "us-west-2";
        const client = new DynamoDB({ region });
        const response = await client.listTables({});
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      render: shell
      description: |
        Run `aws-sdk-js-codemod --version` and paste the result into the form
      placeholder: |
        aws-sdk-js-codemod: 0.10.2

        jscodeshift: 0.14.0
        - babel: 7.20.12
        - babylon: 7.20.7
        - flow: 0.196.3
        - recast: 0.21.5
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
