name: Feature Request
description: A generic feature request about aws-sdk-js-codemod.
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Adding features is a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement this feature"

  - type: textarea
    attributes:
      label: Problem
      description: |
        Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.

        For example, I need transformation for the following code:
        ```ts
        import AWS from "aws-sdk";

        const region = "us-west-2";
        const client = new AWS.DynamoDB({ region });
        const response = await client.listTables({}).promise();
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: |
        A clear and concise description of what you want to happen.

        For example, I'd like the above code to be transformed to:
        ```ts
        import { DynamoDB } from "@aws-sdk/client-dynamodb";

        const region = "us-west-2";
        const client = new DynamoDB({ region });
        const response = await client.listTables({});
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
