name: Feature Request (generic)
description: This is a generic feature request for aws-sdk-js-codemod.
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Adding features is a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement this feature"

  - type: textarea
    attributes:
      label: Problem
      description: |
        Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
