name: Feature Request (transform)
description: These issues are for **concrete and actionable proposals**. If you just have
  a general problem that you would like to brainstorm, open a generic feature request.
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    id: selfservice
    attributes:
      label: Self-service
      description: "Adding features is a great way to give back to open-source projects, and we're more than happy to answer questions and provide context."
      options:
        - label: "I'd be willing to implement this feature"

  - type: dropdown
    id: template-name
    attributes:
      label: Template name
      description: Which template are you adding this feature request for?
      options:
        - v2-to-v3
        - N/A (described above)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Input code
      description: |
        Provide a minimal code for which you need transformation to be supported.
      placeholder: |
        ```ts
        import AWS from "aws-sdk";

        const region = "us-west-2";
        const client = new AWS.DynamoDB({ region });
        const response = await client.listTables({}).promise();
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Output
      description: The expected transformed output for the provided code snippet.
      placeholder: |
        ```ts
        import { DynamoDB } from "@aws-sdk/client-dynamodb";

        const region = "us-west-2";
        const client = new DynamoDB({ region });
        const response = await client.listTables({});
        ```

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. Or a screenshot if applicable.
