import { writeFile } from "fs/promises";
import { join } from "path";

const codegenComment = `// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.`;

const filePath = join("src", "transforms", "v2-to-v3", "config", "CLIENT_TYPES_MAP.ts");
const relativeFilePath = join(__dirname, "..", "..", filePath);

(async () => {
  let fileContent = codegenComment;

  fileContent += `\n\nexport const CLIENT_TYPES_MAP: Record<string, Record<string, string>> = `;

  const clientTypesMap = {};

  fileContent += JSON.stringify(clientTypesMap, null, 2);
  fileContent += `;\n`;

  await writeFile(relativeFilePath, fileContent);
})();
