import { writeFile } from "fs/promises";
import { join } from "path";

import { CLIENT_NAMES } from "../src/transforms/v2-to-v3/utils/config";

const generatedComment = `// This file is generated by scripts/generateNewClientTests.ts`;
const newClientsTestFolder = join("src", "transforms", "v2-to-v3", "__fixtures__", "new-client");
const newClientTestPath = join(__dirname, "..", newClientsTestFolder);

const getGlobalImportInputContent = () => {
  let globalImportInputContent = `${generatedComment}\n`;

  globalImportInputContent += `import AWS from "aws-sdk";\n\n`;
  for (const clientName of CLIENT_NAMES) {
    globalImportInputContent += `new AWS.${clientName}();\n`;
  }

  return globalImportInputContent;
};

(async () => {
  // overwrite `global-import.input.js`
  await writeFile(join(newClientTestPath, `global-import.input.js`), getGlobalImportInputContent());
})();
