import { writeFile } from "fs/promises";
import { join } from "path";

import {
  getGlobalImportInputContent,
  getGlobalImportOutputContent,
} from "./getGlobalImportContent";

const codegenComment = `// This file is generated by scripts/generateNewClientTests.ts`;
const newClientsTestsFolder = join("src", "transforms", "v2-to-v3", "__fixtures__", "new-client");
const newClientTestsPath = join(__dirname, "..", newClientsTestsFolder);

(async () => {
  // overwrite `global-import.input.js`
  const globalImportInputPath = join(newClientTestsPath, `global-import.input.js`);
  await writeFile(globalImportInputPath, getGlobalImportInputContent(codegenComment));

  // overwrite `global-import.output.js`
  const globalImportOutputPath = join(newClientTestsPath, `global-import.output.js`);
  await writeFile(globalImportOutputPath, getGlobalImportOutputContent(codegenComment));
})();
