// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const {
  ACM: ACMClient
} = require("@aws-sdk/client-acm");
const {
  AccessAnalyzer: AccessAnalyzerClient
} = require("@aws-sdk/client-accessanalyzer");
const {
  ApplicationDiscoveryService: DiscoveryClient
} = require("@aws-sdk/client-application-discovery-service");

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
