// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const {
        AccessAnalyzer
      } = require("@aws-sdk/client-accessanalyzer"),
      {
        Account
      } = require("@aws-sdk/client-account"),
      {
        ACM
      } = require("@aws-sdk/client-acm"),
      {
        ACMPCA
      } = require("@aws-sdk/client-acm-pca"),
      {
        AlexaForBusiness
      } = require("@aws-sdk/client-alexa-for-business"),
      {
        Amp
      } = require("@aws-sdk/client-amp"),
      {
        Amplify
      } = require("@aws-sdk/client-amplify"),
      {
        AmplifyBackend
      } = require("@aws-sdk/client-amplifybackend"),
      {
        AmplifyUIBuilder
      } = require("@aws-sdk/client-amplifyuibuilder"),
      {
        APIGateway
      } = require("@aws-sdk/client-api-gateway"),
      {
        ApiGatewayManagementApi
      } = require("@aws-sdk/client-apigatewaymanagementapi"),
      {
        ApiGatewayV2
      } = require("@aws-sdk/client-apigatewayv2"),
      {
        AppMesh
      } = require("@aws-sdk/client-app-mesh"),
      {
        AppConfig
      } = require("@aws-sdk/client-appconfig"),
      {
        AppConfigData
      } = require("@aws-sdk/client-appconfigdata"),
      {
        Appflow
      } = require("@aws-sdk/client-appflow"),
      {
        AppIntegrations
      } = require("@aws-sdk/client-appintegrations"),
      {
        ApplicationAutoScaling
      } = require("@aws-sdk/client-application-auto-scaling"),
      {
        ApplicationDiscoveryService: Discovery
      } = require("@aws-sdk/client-application-discovery-service"),
      {
        ApplicationInsights
      } = require("@aws-sdk/client-application-insights"),
      {
        ApplicationCostProfiler
      } = require("@aws-sdk/client-applicationcostprofiler"),
      {
        AppRunner
      } = require("@aws-sdk/client-apprunner"),
      {
        AppStream
      } = require("@aws-sdk/client-appstream"),
      {
        AppSync
      } = require("@aws-sdk/client-appsync"),
      {
        ARCZonalShift
      } = require("@aws-sdk/client-arc-zonal-shift"),
      {
        Athena
      } = require("@aws-sdk/client-athena"),
      {
        AuditManager
      } = require("@aws-sdk/client-auditmanager"),
      {
        AutoScaling
      } = require("@aws-sdk/client-auto-scaling"),
      {
        AutoScalingPlans
      } = require("@aws-sdk/client-auto-scaling-plans"),
      {
        Backup
      } = require("@aws-sdk/client-backup"),
      {
        BackupGateway
      } = require("@aws-sdk/client-backup-gateway"),
      {
        BackupStorage
      } = require("@aws-sdk/client-backupstorage"),
      {
        Batch
      } = require("@aws-sdk/client-batch"),
      {
        Billingconductor
      } = require("@aws-sdk/client-billingconductor"),
      {
        Braket
      } = require("@aws-sdk/client-braket"),
      {
        Budgets
      } = require("@aws-sdk/client-budgets"),
      {
        Chime
      } = require("@aws-sdk/client-chime"),
      {
        ChimeSDKIdentity
      } = require("@aws-sdk/client-chime-sdk-identity"),
      {
        ChimeSDKMediaPipelines
      } = require("@aws-sdk/client-chime-sdk-media-pipelines"),
      {
        ChimeSDKMeetings
      } = require("@aws-sdk/client-chime-sdk-meetings"),
      {
        ChimeSDKMessaging
      } = require("@aws-sdk/client-chime-sdk-messaging"),
      {
        ChimeSDKVoice
      } = require("@aws-sdk/client-chime-sdk-voice"),
      {
        Cloud9
      } = require("@aws-sdk/client-cloud9"),
      {
        CloudControl
      } = require("@aws-sdk/client-cloudcontrol"),
      {
        CloudDirectory
      } = require("@aws-sdk/client-clouddirectory"),
      {
        CloudFormation
      } = require("@aws-sdk/client-cloudformation"),
      {
        CloudFront
      } = require("@aws-sdk/client-cloudfront"),
      {
        CloudHSM
      } = require("@aws-sdk/client-cloudhsm"),
      {
        CloudHSMV2
      } = require("@aws-sdk/client-cloudhsm-v2"),
      {
        CloudSearch
      } = require("@aws-sdk/client-cloudsearch"),
      {
        CloudSearchDomain
      } = require("@aws-sdk/client-cloudsearch-domain"),
      {
        CloudTrail
      } = require("@aws-sdk/client-cloudtrail"),
      {
        CloudWatch
      } = require("@aws-sdk/client-cloudwatch"),
      {
        CloudWatchEvents
      } = require("@aws-sdk/client-cloudwatch-events"),
      {
        CloudWatchLogs
      } = require("@aws-sdk/client-cloudwatch-logs"),
      {
        Codeartifact: CodeArtifact
      } = require("@aws-sdk/client-codeartifact"),
      {
        CodeBuild
      } = require("@aws-sdk/client-codebuild"),
      {
        CodeCatalyst
      } = require("@aws-sdk/client-codecatalyst"),
      {
        CodeCommit
      } = require("@aws-sdk/client-codecommit"),
      {
        CodeDeploy
      } = require("@aws-sdk/client-codedeploy"),
      {
        CodeGuruReviewer
      } = require("@aws-sdk/client-codeguru-reviewer"),
      {
        CodeGuruProfiler
      } = require("@aws-sdk/client-codeguruprofiler"),
      {
        CodePipeline
      } = require("@aws-sdk/client-codepipeline"),
      {
        CodeStar
      } = require("@aws-sdk/client-codestar"),
      {
        CodeStarConnections: CodeStarconnections
      } = require("@aws-sdk/client-codestar-connections"),
      {
        CodestarNotifications: CodeStarNotifications
      } = require("@aws-sdk/client-codestar-notifications"),
      {
        CognitoIdentity
      } = require("@aws-sdk/client-cognito-identity"),
      {
        CognitoIdentityProvider: CognitoIdentityServiceProvider
      } = require("@aws-sdk/client-cognito-identity-provider"),
      {
        CognitoSync
      } = require("@aws-sdk/client-cognito-sync"),
      {
        Comprehend
      } = require("@aws-sdk/client-comprehend"),
      {
        ComprehendMedical
      } = require("@aws-sdk/client-comprehendmedical"),
      {
        ComputeOptimizer
      } = require("@aws-sdk/client-compute-optimizer"),
      {
        ConfigService
      } = require("@aws-sdk/client-config-service"),
      {
        Connect
      } = require("@aws-sdk/client-connect"),
      {
        ConnectContactLens
      } = require("@aws-sdk/client-connect-contact-lens"),
      {
        ConnectCampaigns
      } = require("@aws-sdk/client-connectcampaigns"),
      {
        ConnectCases
      } = require("@aws-sdk/client-connectcases"),
      {
        ConnectParticipant
      } = require("@aws-sdk/client-connectparticipant"),
      {
        ControlTower
      } = require("@aws-sdk/client-controltower"),
      {
        CostAndUsageReportService: CUR
      } = require("@aws-sdk/client-cost-and-usage-report-service"),
      {
        CostExplorer
      } = require("@aws-sdk/client-cost-explorer"),
      {
        CustomerProfiles
      } = require("@aws-sdk/client-customer-profiles"),
      {
        DataPipeline
      } = require("@aws-sdk/client-data-pipeline"),
      {
        DatabaseMigrationService: DMS
      } = require("@aws-sdk/client-database-migration-service"),
      {
        DataBrew
      } = require("@aws-sdk/client-databrew"),
      {
        DataExchange
      } = require("@aws-sdk/client-dataexchange"),
      {
        DataSync
      } = require("@aws-sdk/client-datasync"),
      {
        DAX
      } = require("@aws-sdk/client-dax"),
      {
        Detective
      } = require("@aws-sdk/client-detective"),
      {
        DeviceFarm
      } = require("@aws-sdk/client-device-farm"),
      {
        DevOpsGuru
      } = require("@aws-sdk/client-devops-guru"),
      {
        DirectConnect
      } = require("@aws-sdk/client-direct-connect"),
      {
        DirectoryService
      } = require("@aws-sdk/client-directory-service"),
      {
        DLM
      } = require("@aws-sdk/client-dlm"),
      {
        DocDB
      } = require("@aws-sdk/client-docdb"),
      {
        DocDBElastic
      } = require("@aws-sdk/client-docdb-elastic"),
      {
        Drs
      } = require("@aws-sdk/client-drs"),
      {
        DynamoDB
      } = require("@aws-sdk/client-dynamodb"),
      {
        DynamoDBStreams
      } = require("@aws-sdk/client-dynamodb-streams"),
      {
        EBS
      } = require("@aws-sdk/client-ebs"),
      {
        EC2
      } = require("@aws-sdk/client-ec2"),
      {
        EC2InstanceConnect
      } = require("@aws-sdk/client-ec2-instance-connect"),
      {
        ECR
      } = require("@aws-sdk/client-ecr"),
      {
        ECRPUBLIC
      } = require("@aws-sdk/client-ecr-public"),
      {
        ECS
      } = require("@aws-sdk/client-ecs"),
      {
        EFS
      } = require("@aws-sdk/client-efs"),
      {
        EKS
      } = require("@aws-sdk/client-eks"),
      {
        ElasticBeanstalk
      } = require("@aws-sdk/client-elastic-beanstalk"),
      {
        ElasticInference
      } = require("@aws-sdk/client-elastic-inference"),
      {
        ElasticLoadBalancing: ELB
      } = require("@aws-sdk/client-elastic-load-balancing"),
      {
        ElasticLoadBalancingV2: ELBv2
      } = require("@aws-sdk/client-elastic-load-balancing-v2"),
      {
        ElasticTranscoder
      } = require("@aws-sdk/client-elastic-transcoder"),
      {
        ElastiCache
      } = require("@aws-sdk/client-elasticache"),
      {
        ElasticsearchService: ES
      } = require("@aws-sdk/client-elasticsearch-service"),
      {
        EMR
      } = require("@aws-sdk/client-emr"),
      {
        EMRContainers: EMRcontainers
      } = require("@aws-sdk/client-emr-containers"),
      {
        EMRServerless
      } = require("@aws-sdk/client-emr-serverless"),
      {
        EventBridge
      } = require("@aws-sdk/client-eventbridge"),
      {
        Evidently
      } = require("@aws-sdk/client-evidently"),
      {
        Finspace
      } = require("@aws-sdk/client-finspace"),
      {
        FinspaceData: Finspacedata
      } = require("@aws-sdk/client-finspace-data"),
      {
        Firehose
      } = require("@aws-sdk/client-firehose"),
      {
        Fis
      } = require("@aws-sdk/client-fis"),
      {
        FMS
      } = require("@aws-sdk/client-fms"),
      {
        Forecast: ForecastService
      } = require("@aws-sdk/client-forecast"),
      {
        Forecastquery: ForecastQueryService
      } = require("@aws-sdk/client-forecastquery"),
      {
        FraudDetector
      } = require("@aws-sdk/client-frauddetector"),
      {
        FSx
      } = require("@aws-sdk/client-fsx"),
      {
        GameLift
      } = require("@aws-sdk/client-gamelift"),
      {
        GameSparks
      } = require("@aws-sdk/client-gamesparks"),
      {
        Glacier
      } = require("@aws-sdk/client-glacier"),
      {
        GlobalAccelerator
      } = require("@aws-sdk/client-global-accelerator"),
      {
        Glue
      } = require("@aws-sdk/client-glue"),
      {
        Grafana
      } = require("@aws-sdk/client-grafana"),
      {
        Greengrass
      } = require("@aws-sdk/client-greengrass"),
      {
        GreengrassV2
      } = require("@aws-sdk/client-greengrassv2"),
      {
        GroundStation
      } = require("@aws-sdk/client-groundstation"),
      {
        GuardDuty
      } = require("@aws-sdk/client-guardduty"),
      {
        Health
      } = require("@aws-sdk/client-health"),
      {
        HealthLake
      } = require("@aws-sdk/client-healthlake"),
      {
        Honeycode
      } = require("@aws-sdk/client-honeycode"),
      {
        IAM
      } = require("@aws-sdk/client-iam"),
      {
        Identitystore: IdentityStore
      } = require("@aws-sdk/client-identitystore"),
      {
        Imagebuilder
      } = require("@aws-sdk/client-imagebuilder"),
      {
        Inspector
      } = require("@aws-sdk/client-inspector"),
      {
        Inspector2
      } = require("@aws-sdk/client-inspector2"),
      {
        IoT: Iot
      } = require("@aws-sdk/client-iot"),
      {
        IoT1ClickDevicesService
      } = require("@aws-sdk/client-iot-1click-devices-service"),
      {
        IoT1ClickProjects
      } = require("@aws-sdk/client-iot-1click-projects"),
      {
        IoTDataPlane: IotData
      } = require("@aws-sdk/client-iot-data-plane"),
      {
        IoTEvents
      } = require("@aws-sdk/client-iot-events"),
      {
        IoTEventsData
      } = require("@aws-sdk/client-iot-events-data"),
      {
        IoTJobsDataPlane
      } = require("@aws-sdk/client-iot-jobs-data-plane"),
      {
        IoTRoboRunner
      } = require("@aws-sdk/client-iot-roborunner"),
      {
        IoTWireless
      } = require("@aws-sdk/client-iot-wireless"),
      {
        IoTAnalytics
      } = require("@aws-sdk/client-iotanalytics"),
      {
        IotDeviceAdvisor
      } = require("@aws-sdk/client-iotdeviceadvisor"),
      {
        IoTFleetHub
      } = require("@aws-sdk/client-iotfleethub"),
      {
        IoTFleetWise
      } = require("@aws-sdk/client-iotfleetwise"),
      {
        IoTSecureTunneling
      } = require("@aws-sdk/client-iotsecuretunneling"),
      {
        IoTSiteWise
      } = require("@aws-sdk/client-iotsitewise"),
      {
        IoTThingsGraph
      } = require("@aws-sdk/client-iotthingsgraph"),
      {
        IoTTwinMaker
      } = require("@aws-sdk/client-iottwinmaker"),
      {
        Ivs: IVS
      } = require("@aws-sdk/client-ivs"),
      {
        Ivschat
      } = require("@aws-sdk/client-ivschat"),
      {
        Kafka
      } = require("@aws-sdk/client-kafka"),
      {
        KafkaConnect
      } = require("@aws-sdk/client-kafkaconnect"),
      {
        Kendra
      } = require("@aws-sdk/client-kendra"),
      {
        Keyspaces
      } = require("@aws-sdk/client-keyspaces"),
      {
        Kinesis
      } = require("@aws-sdk/client-kinesis"),
      {
        KinesisAnalytics
      } = require("@aws-sdk/client-kinesis-analytics"),
      {
        KinesisAnalyticsV2
      } = require("@aws-sdk/client-kinesis-analytics-v2"),
      {
        KinesisVideo
      } = require("@aws-sdk/client-kinesis-video"),
      {
        KinesisVideoArchivedMedia
      } = require("@aws-sdk/client-kinesis-video-archived-media"),
      {
        KinesisVideoMedia
      } = require("@aws-sdk/client-kinesis-video-media"),
      {
        KinesisVideoSignaling: KinesisVideoSignalingChannels
      } = require("@aws-sdk/client-kinesis-video-signaling"),
      {
        KinesisVideoWebRTCStorage
      } = require("@aws-sdk/client-kinesis-video-webrtc-storage"),
      {
        KMS
      } = require("@aws-sdk/client-kms"),
      {
        LakeFormation
      } = require("@aws-sdk/client-lakeformation"),
      {
        Lambda
      } = require("@aws-sdk/client-lambda"),
      {
        LexModelBuildingService
      } = require("@aws-sdk/client-lex-model-building-service"),
      {
        LexModelsV2
      } = require("@aws-sdk/client-lex-models-v2"),
      {
        LexRuntimeService: LexRuntime
      } = require("@aws-sdk/client-lex-runtime-service"),
      {
        LexRuntimeV2
      } = require("@aws-sdk/client-lex-runtime-v2"),
      {
        LicenseManager
      } = require("@aws-sdk/client-license-manager"),
      {
        LicenseManagerLinuxSubscriptions
      } = require("@aws-sdk/client-license-manager-linux-subscriptions"),
      {
        LicenseManagerUserSubscriptions
      } = require("@aws-sdk/client-license-manager-user-subscriptions"),
      {
        Lightsail
      } = require("@aws-sdk/client-lightsail"),
      {
        Location
      } = require("@aws-sdk/client-location"),
      {
        LookoutEquipment
      } = require("@aws-sdk/client-lookoutequipment"),
      {
        LookoutMetrics
      } = require("@aws-sdk/client-lookoutmetrics"),
      {
        LookoutVision
      } = require("@aws-sdk/client-lookoutvision"),
      {
        M2
      } = require("@aws-sdk/client-m2"),
      {
        MachineLearning
      } = require("@aws-sdk/client-machine-learning"),
      {
        Macie
      } = require("@aws-sdk/client-macie"),
      {
        Macie2
      } = require("@aws-sdk/client-macie2"),
      {
        ManagedBlockchain
      } = require("@aws-sdk/client-managedblockchain"),
      {
        MarketplaceCatalog
      } = require("@aws-sdk/client-marketplace-catalog"),
      {
        MarketplaceCommerceAnalytics
      } = require("@aws-sdk/client-marketplace-commerce-analytics"),
      {
        MarketplaceEntitlementService
      } = require("@aws-sdk/client-marketplace-entitlement-service"),
      {
        MarketplaceMetering
      } = require("@aws-sdk/client-marketplace-metering"),
      {
        MediaConnect
      } = require("@aws-sdk/client-mediaconnect"),
      {
        MediaConvert
      } = require("@aws-sdk/client-mediaconvert"),
      {
        MediaLive
      } = require("@aws-sdk/client-medialive"),
      {
        MediaPackage
      } = require("@aws-sdk/client-mediapackage"),
      {
        MediaPackageVod
      } = require("@aws-sdk/client-mediapackage-vod"),
      {
        MediaStore
      } = require("@aws-sdk/client-mediastore"),
      {
        MediaStoreData
      } = require("@aws-sdk/client-mediastore-data"),
      {
        MediaTailor
      } = require("@aws-sdk/client-mediatailor"),
      {
        MemoryDB
      } = require("@aws-sdk/client-memory-db"),
      {
        Mgn
      } = require("@aws-sdk/client-mgn"),
      {
        MigrationHub
      } = require("@aws-sdk/client-migration-hub"),
      {
        MigrationHubRefactorSpaces
      } = require("@aws-sdk/client-migration-hub-refactor-spaces"),
      {
        MigrationHubConfig
      } = require("@aws-sdk/client-migrationhub-config"),
      {
        MigrationHubOrchestrator
      } = require("@aws-sdk/client-migrationhuborchestrator"),
      {
        MigrationHubStrategy
      } = require("@aws-sdk/client-migrationhubstrategy"),
      {
        Mobile
      } = require("@aws-sdk/client-mobile"),
      {
        Mq: MQ
      } = require("@aws-sdk/client-mq"),
      {
        MTurk
      } = require("@aws-sdk/client-mturk"),
      {
        MWAA
      } = require("@aws-sdk/client-mwaa"),
      {
        Neptune
      } = require("@aws-sdk/client-neptune"),
      {
        NetworkFirewall
      } = require("@aws-sdk/client-network-firewall"),
      {
        NetworkManager
      } = require("@aws-sdk/client-networkmanager"),
      {
        Nimble
      } = require("@aws-sdk/client-nimble"),
      {
        OAM
      } = require("@aws-sdk/client-oam"),
      {
        Omics
      } = require("@aws-sdk/client-omics"),
      {
        OpenSearch
      } = require("@aws-sdk/client-opensearch"),
      {
        OpenSearchServerless
      } = require("@aws-sdk/client-opensearchserverless"),
      {
        OpsWorks
      } = require("@aws-sdk/client-opsworks"),
      {
        OpsWorksCM
      } = require("@aws-sdk/client-opsworkscm"),
      {
        Organizations
      } = require("@aws-sdk/client-organizations"),
      {
        Outposts
      } = require("@aws-sdk/client-outposts"),
      {
        Panorama
      } = require("@aws-sdk/client-panorama"),
      {
        Personalize
      } = require("@aws-sdk/client-personalize"),
      {
        PersonalizeEvents
      } = require("@aws-sdk/client-personalize-events"),
      {
        PersonalizeRuntime
      } = require("@aws-sdk/client-personalize-runtime"),
      {
        PI
      } = require("@aws-sdk/client-pi"),
      {
        Pinpoint
      } = require("@aws-sdk/client-pinpoint"),
      {
        PinpointEmail
      } = require("@aws-sdk/client-pinpoint-email"),
      {
        PinpointSMSVoice
      } = require("@aws-sdk/client-pinpoint-sms-voice"),
      {
        PinpointSMSVoiceV2
      } = require("@aws-sdk/client-pinpoint-sms-voice-v2"),
      {
        Pipes
      } = require("@aws-sdk/client-pipes"),
      {
        Polly
      } = require("@aws-sdk/client-polly"),
      {
        Pricing
      } = require("@aws-sdk/client-pricing"),
      {
        PrivateNetworks
      } = require("@aws-sdk/client-privatenetworks"),
      {
        Proton
      } = require("@aws-sdk/client-proton"),
      {
        QLDB
      } = require("@aws-sdk/client-qldb"),
      {
        QLDBSession
      } = require("@aws-sdk/client-qldb-session"),
      {
        QuickSight
      } = require("@aws-sdk/client-quicksight"),
      {
        RAM
      } = require("@aws-sdk/client-ram"),
      {
        Rbin
      } = require("@aws-sdk/client-rbin"),
      {
        RDS
      } = require("@aws-sdk/client-rds"),
      {
        RDSData: RDSDataService
      } = require("@aws-sdk/client-rds-data"),
      {
        Redshift
      } = require("@aws-sdk/client-redshift"),
      {
        RedshiftData
      } = require("@aws-sdk/client-redshift-data"),
      {
        RedshiftServerless
      } = require("@aws-sdk/client-redshift-serverless"),
      {
        Rekognition
      } = require("@aws-sdk/client-rekognition"),
      {
        Resiliencehub
      } = require("@aws-sdk/client-resiliencehub"),
      {
        ResourceExplorer2
      } = require("@aws-sdk/client-resource-explorer-2"),
      {
        ResourceGroups
      } = require("@aws-sdk/client-resource-groups"),
      {
        ResourceGroupsTaggingAPI
      } = require("@aws-sdk/client-resource-groups-tagging-api"),
      {
        RoboMaker
      } = require("@aws-sdk/client-robomaker"),
      {
        RolesAnywhere
      } = require("@aws-sdk/client-rolesanywhere"),
      {
        Route53
      } = require("@aws-sdk/client-route-53"),
      {
        Route53Domains
      } = require("@aws-sdk/client-route-53-domains"),
      {
        Route53RecoveryCluster
      } = require("@aws-sdk/client-route53-recovery-cluster"),
      {
        Route53RecoveryControlConfig
      } = require("@aws-sdk/client-route53-recovery-control-config"),
      {
        Route53RecoveryReadiness
      } = require("@aws-sdk/client-route53-recovery-readiness"),
      {
        Route53Resolver
      } = require("@aws-sdk/client-route53resolver"),
      {
        RUM
      } = require("@aws-sdk/client-rum"),
      {
        S3
      } = require("@aws-sdk/client-s3"),
      {
        S3Control
      } = require("@aws-sdk/client-s3-control"),
      {
        S3Outposts
      } = require("@aws-sdk/client-s3outposts"),
      {
        SageMakerA2IRuntime: AugmentedAIRuntime
      } = require("@aws-sdk/client-sage-maker-a2iruntime"),
      {
        SageMaker
      } = require("@aws-sdk/client-sagemaker"),
      {
        SagemakerEdge
      } = require("@aws-sdk/client-sagemaker-edge"),
      {
        SageMakerFeatureStoreRuntime
      } = require("@aws-sdk/client-sagemaker-featurestore-runtime"),
      {
        SageMakerGeospatial
      } = require("@aws-sdk/client-sagemaker-geospatial"),
      {
        SageMakerMetrics
      } = require("@aws-sdk/client-sagemaker-metrics"),
      {
        SageMakerRuntime
      } = require("@aws-sdk/client-sagemaker-runtime"),
      {
        Savingsplans: SavingsPlans
      } = require("@aws-sdk/client-savingsplans"),
      {
        Scheduler
      } = require("@aws-sdk/client-scheduler"),
      {
        Schemas
      } = require("@aws-sdk/client-schemas"),
      {
        SecretsManager
      } = require("@aws-sdk/client-secrets-manager"),
      {
        SecurityHub
      } = require("@aws-sdk/client-securityhub"),
      {
        SecurityLake
      } = require("@aws-sdk/client-securitylake"),
      {
        ServerlessApplicationRepository
      } = require("@aws-sdk/client-serverlessapplicationrepository"),
      {
        ServiceCatalog
      } = require("@aws-sdk/client-service-catalog"),
      {
        ServiceCatalogAppRegistry
      } = require("@aws-sdk/client-service-catalog-appregistry"),
      {
        ServiceQuotas
      } = require("@aws-sdk/client-service-quotas"),
      {
        ServiceDiscovery
      } = require("@aws-sdk/client-servicediscovery"),
      {
        SES
      } = require("@aws-sdk/client-ses"),
      {
        SESv2: SESV2
      } = require("@aws-sdk/client-sesv2"),
      {
        SFN: StepFunctions
      } = require("@aws-sdk/client-sfn"),
      {
        Shield
      } = require("@aws-sdk/client-shield"),
      {
        Signer
      } = require("@aws-sdk/client-signer"),
      {
        SimSpaceWeaver
      } = require("@aws-sdk/client-simspaceweaver"),
      {
        SMS
      } = require("@aws-sdk/client-sms"),
      {
        SnowDeviceManagement
      } = require("@aws-sdk/client-snow-device-management"),
      {
        Snowball
      } = require("@aws-sdk/client-snowball"),
      {
        SNS
      } = require("@aws-sdk/client-sns"),
      {
        SQS
      } = require("@aws-sdk/client-sqs"),
      {
        SSM
      } = require("@aws-sdk/client-ssm"),
      {
        SSMContacts
      } = require("@aws-sdk/client-ssm-contacts"),
      {
        SSMIncidents
      } = require("@aws-sdk/client-ssm-incidents"),
      {
        SsmSap
      } = require("@aws-sdk/client-ssm-sap"),
      {
        SSO
      } = require("@aws-sdk/client-sso"),
      {
        SSOAdmin
      } = require("@aws-sdk/client-sso-admin"),
      {
        SSOOIDC
      } = require("@aws-sdk/client-sso-oidc"),
      {
        StorageGateway
      } = require("@aws-sdk/client-storage-gateway"),
      {
        STS
      } = require("@aws-sdk/client-sts"),
      {
        Support
      } = require("@aws-sdk/client-support"),
      {
        SupportApp
      } = require("@aws-sdk/client-support-app"),
      {
        SWF
      } = require("@aws-sdk/client-swf"),
      {
        Synthetics
      } = require("@aws-sdk/client-synthetics"),
      {
        Textract
      } = require("@aws-sdk/client-textract"),
      {
        TimestreamQuery
      } = require("@aws-sdk/client-timestream-query"),
      {
        TimestreamWrite
      } = require("@aws-sdk/client-timestream-write"),
      {
        Transcribe: TranscribeService
      } = require("@aws-sdk/client-transcribe"),
      {
        Transfer
      } = require("@aws-sdk/client-transfer"),
      {
        Translate
      } = require("@aws-sdk/client-translate"),
      {
        VoiceID
      } = require("@aws-sdk/client-voice-id"),
      {
        WAF
      } = require("@aws-sdk/client-waf"),
      {
        WAFRegional
      } = require("@aws-sdk/client-waf-regional"),
      {
        WAFV2
      } = require("@aws-sdk/client-wafv2"),
      {
        WellArchitected
      } = require("@aws-sdk/client-wellarchitected"),
      {
        Wisdom
      } = require("@aws-sdk/client-wisdom"),
      {
        WorkDocs
      } = require("@aws-sdk/client-workdocs"),
      {
        WorkLink
      } = require("@aws-sdk/client-worklink"),
      {
        WorkMail
      } = require("@aws-sdk/client-workmail"),
      {
        WorkMailMessageFlow
      } = require("@aws-sdk/client-workmailmessageflow"),
      {
        WorkSpaces
      } = require("@aws-sdk/client-workspaces"),
      {
        WorkSpacesWeb
      } = require("@aws-sdk/client-workspaces-web"),
      {
        XRay
      } = require("@aws-sdk/client-xray");

new ACM();
new ACMPCA();
new APIGateway();
new ARCZonalShift();
new AccessAnalyzer();
new Account();
new AlexaForBusiness();
new Amp();
new Amplify();
new AmplifyBackend();
new AmplifyUIBuilder();
new ApiGatewayManagementApi();
new ApiGatewayV2();
new AppConfig();
new AppConfigData();
new AppIntegrations();
new AppMesh();
new AppRunner();
new AppStream();
new AppSync();
new Appflow();
new ApplicationAutoScaling();
new ApplicationCostProfiler();
new ApplicationInsights();
new Athena();
new AuditManager();
new AugmentedAIRuntime();
new AutoScaling();
new AutoScalingPlans();
new Backup();
new BackupGateway();
new BackupStorage();
new Batch();
new Billingconductor();
new Braket();
new Budgets();
new CUR();
new Chime();
new ChimeSDKIdentity();
new ChimeSDKMediaPipelines();
new ChimeSDKMeetings();
new ChimeSDKMessaging();
new ChimeSDKVoice();
new Cloud9();
new CloudControl();
new CloudDirectory();
new CloudFormation();
new CloudFront();
new CloudHSM();
new CloudHSMV2();
new CloudSearch();
new CloudSearchDomain();
new CloudTrail();
new CloudWatch();
new CloudWatchEvents();
new CloudWatchLogs();
new CodeArtifact();
new CodeBuild();
new CodeCatalyst();
new CodeCommit();
new CodeDeploy();
new CodeGuruProfiler();
new CodeGuruReviewer();
new CodePipeline();
new CodeStar();
new CodeStarNotifications();
new CodeStarconnections();
new CognitoIdentity();
new CognitoIdentityServiceProvider();
new CognitoSync();
new Comprehend();
new ComprehendMedical();
new ComputeOptimizer();
new ConfigService();
new Connect();
new ConnectCampaigns();
new ConnectCases();
new ConnectContactLens();
new ConnectParticipant();
new ControlTower();
new CostExplorer();
new CustomerProfiles();
new DAX();
new DLM();
new DMS();
new DataBrew();
new DataExchange();
new DataPipeline();
new DataSync();
new Detective();
new DevOpsGuru();
new DeviceFarm();
new DirectConnect();
new DirectoryService();
new Discovery();
new DocDB();
new DocDBElastic();
new Drs();
new DynamoDB();
new DynamoDBStreams();
new EBS();
new EC2();
new EC2InstanceConnect();
new ECR();
new ECRPUBLIC();
new ECS();
new EFS();
new EKS();
new ELB();
new ELBv2();
new EMR();
new EMRServerless();
new EMRcontainers();
new ES();
new ElastiCache();
new ElasticBeanstalk();
new ElasticInference();
new ElasticTranscoder();
new EventBridge();
new Evidently();
new FMS();
new FSx();
new Finspace();
new Finspacedata();
new Firehose();
new Fis();
new ForecastQueryService();
new ForecastService();
new FraudDetector();
new GameLift();
new GameSparks();
new Glacier();
new GlobalAccelerator();
new Glue();
new Grafana();
new Greengrass();
new GreengrassV2();
new GroundStation();
new GuardDuty();
new Health();
new HealthLake();
new Honeycode();
new IAM();
new IVS();
new IdentityStore();
new Imagebuilder();
new Inspector();
new Inspector2();
new IoT1ClickDevicesService();
new IoT1ClickProjects();
new IoTAnalytics();
new IoTEvents();
new IoTEventsData();
new IoTFleetHub();
new IoTFleetWise();
new IoTJobsDataPlane();
new IoTRoboRunner();
new IoTSecureTunneling();
new IoTSiteWise();
new IoTThingsGraph();
new IoTTwinMaker();
new IoTWireless();
new Iot();
new IotData();
new IotDeviceAdvisor();
new Ivschat();
new KMS();
new Kafka();
new KafkaConnect();
new Kendra();
new Keyspaces();
new Kinesis();
new KinesisAnalytics();
new KinesisAnalyticsV2();
new KinesisVideo();
new KinesisVideoArchivedMedia();
new KinesisVideoMedia();
new KinesisVideoSignalingChannels();
new KinesisVideoWebRTCStorage();
new LakeFormation();
new Lambda();
new LexModelBuildingService();
new LexModelsV2();
new LexRuntime();
new LexRuntimeV2();
new LicenseManager();
new LicenseManagerLinuxSubscriptions();
new LicenseManagerUserSubscriptions();
new Lightsail();
new Location();
new LookoutEquipment();
new LookoutMetrics();
new LookoutVision();
new M2();
new MQ();
new MTurk();
new MWAA();
new MachineLearning();
new Macie();
new Macie2();
new ManagedBlockchain();
new MarketplaceCatalog();
new MarketplaceCommerceAnalytics();
new MarketplaceEntitlementService();
new MarketplaceMetering();
new MediaConnect();
new MediaConvert();
new MediaLive();
new MediaPackage();
new MediaPackageVod();
new MediaStore();
new MediaStoreData();
new MediaTailor();
new MemoryDB();
new Mgn();
new MigrationHub();
new MigrationHubConfig();
new MigrationHubOrchestrator();
new MigrationHubRefactorSpaces();
new MigrationHubStrategy();
new Mobile();
new Neptune();
new NetworkFirewall();
new NetworkManager();
new Nimble();
new OAM();
new Omics();
new OpenSearch();
new OpenSearchServerless();
new OpsWorks();
new OpsWorksCM();
new Organizations();
new Outposts();
new PI();
new Panorama();
new Personalize();
new PersonalizeEvents();
new PersonalizeRuntime();
new Pinpoint();
new PinpointEmail();
new PinpointSMSVoice();
new PinpointSMSVoiceV2();
new Pipes();
new Polly();
new Pricing();
new PrivateNetworks();
new Proton();
new QLDB();
new QLDBSession();
new QuickSight();
new RAM();
new RDS();
new RDSDataService();
new RUM();
new Rbin();
new Redshift();
new RedshiftData();
new RedshiftServerless();
new Rekognition();
new Resiliencehub();
new ResourceExplorer2();
new ResourceGroups();
new ResourceGroupsTaggingAPI();
new RoboMaker();
new RolesAnywhere();
new Route53();
new Route53Domains();
new Route53RecoveryCluster();
new Route53RecoveryControlConfig();
new Route53RecoveryReadiness();
new Route53Resolver();
new S3();
new S3Control();
new S3Outposts();
new SES();
new SESV2();
new SMS();
new SNS();
new SQS();
new SSM();
new SSMContacts();
new SSMIncidents();
new SSO();
new SSOAdmin();
new SSOOIDC();
new STS();
new SWF();
new SageMaker();
new SageMakerFeatureStoreRuntime();
new SageMakerGeospatial();
new SageMakerMetrics();
new SageMakerRuntime();
new SagemakerEdge();
new SavingsPlans();
new Scheduler();
new Schemas();
new SecretsManager();
new SecurityHub();
new SecurityLake();
new ServerlessApplicationRepository();
new ServiceCatalog();
new ServiceCatalogAppRegistry();
new ServiceDiscovery();
new ServiceQuotas();
new Shield();
new Signer();
new SimSpaceWeaver();
new SnowDeviceManagement();
new Snowball();
new SsmSap();
new StepFunctions();
new StorageGateway();
new Support();
new SupportApp();
new Synthetics();
new Textract();
new TimestreamQuery();
new TimestreamWrite();
new TranscribeService();
new Transfer();
new Translate();
new VoiceID();
new WAF();
new WAFRegional();
new WAFV2();
new WellArchitected();
new Wisdom();
new WorkDocs();
new WorkLink();
new WorkMail();
new WorkMailMessageFlow();
new WorkSpaces();
new WorkSpacesWeb();
new XRay();
