// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.


import AWS_AccessAnalyzer = require("@aws-sdk/client-accessanalyzer");
import AccessAnalyzer = AWS_AccessAnalyzer.AccessAnalyzer;
import AWS_ACM = require("@aws-sdk/client-acm");
import ACM = AWS_ACM.ACM;
import AWS_Discovery = require("@aws-sdk/client-application-discovery-service");
import ApplicationDiscoveryService = AWS_Discovery.ApplicationDiscoveryService;

new ACM();
new AccessAnalyzer();
new ApplicationDiscoveryService();
