// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.


import AWS_AccessAnalyzer = require("@aws-sdk/client-accessanalyzer");
import AWS_ACM = require("@aws-sdk/client-acm");
import AWS_Discovery = require("@aws-sdk/client-application-discovery-service");

new AWS_ACM.ACM();
new AWS_AccessAnalyzer.AccessAnalyzer();
new AWS_Discovery.ApplicationDiscoveryService();
