// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const AWS_AccessAnalyzer = require("@aws-sdk/client-accessanalyzer"),
      AWS_ACM = require("@aws-sdk/client-acm"),
      AWS_Discovery = require("@aws-sdk/client-application-discovery-service");
const { 
  AccessAnalyzer
} = AWS_AccessAnalyzer;
const { 
  ACM
} = AWS_ACM;
const { 
  ApplicationDiscoveryService: Discovery
} = AWS_Discovery;

new ACM();
new AccessAnalyzer();
new Discovery();
