// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import * as AWS from "aws-sdk";

new AWS.ACM();
new AWS.AccessAnalyzer();
new AWS.Discovery();
