// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const ACM = require("aws-sdk").ACM;
const AccessAnalyzer = require("aws-sdk").AccessAnalyzer;
const Discovery = require("aws-sdk").Discovery;

new ACM();
new AccessAnalyzer();
new Discovery();
