// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const {
  ACM
} = require("@aws-sdk/client-acm");
const {
  AccessAnalyzer
} = require("@aws-sdk/client-accessanalyzer");
const {
  ApplicationDiscoveryService
} = require("@aws-sdk/client-application-discovery-service");

new ACM();
new AccessAnalyzer();
new Discovery();
