// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const ACMClient = require("aws-sdk").ACM;
const AccessAnalyzerClient = require("aws-sdk").AccessAnalyzer;
const DiscoveryClient = require("aws-sdk").Discovery;

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
