// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import AccessAnalyzerClient from "aws-sdk/clients/accessanalyzer";
import DiscoveryClient from "aws-sdk/clients/discovery";
import ACMClient from "aws-sdk/clients/acm";

new AccessAnalyzerClient();
new DiscoveryClient();
new ACMClient();
