// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import ACMClient = require("aws-sdk/clients/acm");
import AccessAnalyzerClient = require("aws-sdk/clients/accessanalyzer");
import DiscoveryClient = require("aws-sdk/clients/discovery");

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
