// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.


import { ACM } from "@aws-sdk/client-acm";
import { AccessAnalyzer } from "@aws-sdk/client-accessanalyzer";
import { ApplicationDiscoveryService as Discovery } from "@aws-sdk/client-application-discovery-service";

new ACM();
new AccessAnalyzer();
new Discovery();
