// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import { AccessAnalyzer, Discovery, ACM } from "aws-sdk/clients/all";

new AccessAnalyzer();
new Discovery();
new ACM();
