// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const { AccessAnalyzer, Discovery, ACM } = require("aws-sdk");

new AccessAnalyzer();
new Discovery();
new ACM();
