// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
import { ACM as ACMClient } from "@aws-sdk/client-acm";
import { AccessAnalyzer as AccessAnalyzerClient } from "@aws-sdk/client-accessanalyzer";
import { ApplicationDiscoveryService as DiscoveryClient } from "@aws-sdk/client-application-discovery-service";

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
