// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import { 
  AccessAnalyzer as AccessAnalyzerClient,
  Discovery as DiscoveryClient,
  ACM as ACMClient
} from "aws-sdk";

new AccessAnalyzerClient();
new DiscoveryClient();
new ACMClient();
