// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import AccessAnalyzer from "aws-sdk/clients/accessanalyzer";
import Discovery from "aws-sdk/clients/discovery";
import ACM from "aws-sdk/clients/acm";

new AccessAnalyzer();
new Discovery();
new ACM();
