// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const AccessAnalyzer = require("aws-sdk/clients/accessanalyzer");
const Discovery = require("aws-sdk/clients/discovery");
const ACM = require("aws-sdk/clients/acm");

new AccessAnalyzer();
new Discovery();
new ACM();
