// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const { 
  AccessAnalyzer: AccessAnalyzerClient,
  Discovery: DiscoveryClient,
  ACM: ACMClient
} = require("aws-sdk");

new AccessAnalyzerClient();
new DiscoveryClient();
new ACMClient();
