// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const { ACM, AccessAnalyzer, Discovery } = require("aws-sdk");

new ACM();
new AccessAnalyzer();
new Discovery();
