// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import { 
  ACM as ACMClient,
  AccessAnalyzer as AccessAnalyzerClient,
  Discovery as DiscoveryClient
} from "aws-sdk";

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
