// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const AccessAnalyzerClient = require("aws-sdk/clients/accessanalyzer");
const DiscoveryClient = require("aws-sdk/clients/discovery");
const ACMClient = require("aws-sdk/clients/acm");

new AccessAnalyzerClient();
new DiscoveryClient();
new ACMClient();
