// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const ACM = require("aws-sdk/clients/acm");
const AccessAnalyzer = require("aws-sdk/clients/accessanalyzer");
const Discovery = require("aws-sdk/clients/discovery");

new ACM();
new AccessAnalyzer();
new Discovery();
