// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const ACMClient = require("aws-sdk/clients/acm");
const AccessAnalyzerClient = require("aws-sdk/clients/accessanalyzer");
const DiscoveryClient = require("aws-sdk/clients/discovery");

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
