// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const {
  ACM
} = require("@aws-sdk/client-acm");
const {
  ACMPCA
} = require("@aws-sdk/client-acm-pca");
const {
  APIGateway
} = require("@aws-sdk/client-api-gateway");
const {
  ARCZonalShift
} = require("@aws-sdk/client-arc-zonal-shift");
const {
  AccessAnalyzer
} = require("@aws-sdk/client-accessanalyzer");
const {
  Account
} = require("@aws-sdk/client-account");
const {
  AlexaForBusiness
} = require("@aws-sdk/client-alexa-for-business");
const {
  Amp
} = require("@aws-sdk/client-amp");
const {
  Amplify
} = require("@aws-sdk/client-amplify");
const {
  AmplifyBackend
} = require("@aws-sdk/client-amplifybackend");
const {
  AmplifyUIBuilder
} = require("@aws-sdk/client-amplifyuibuilder");
const {
  ApiGatewayManagementApi
} = require("@aws-sdk/client-apigatewaymanagementapi");
const {
  ApiGatewayV2
} = require("@aws-sdk/client-apigatewayv2");
const {
  AppConfig
} = require("@aws-sdk/client-appconfig");
const {
  AppConfigData
} = require("@aws-sdk/client-appconfigdata");
const {
  AppIntegrations
} = require("@aws-sdk/client-appintegrations");
const {
  AppMesh
} = require("@aws-sdk/client-app-mesh");
const {
  AppRunner
} = require("@aws-sdk/client-apprunner");
const {
  AppStream
} = require("@aws-sdk/client-appstream");
const {
  AppSync
} = require("@aws-sdk/client-appsync");
const {
  Appflow
} = require("@aws-sdk/client-appflow");
const {
  ApplicationAutoScaling
} = require("@aws-sdk/client-application-auto-scaling");
const {
  ApplicationCostProfiler
} = require("@aws-sdk/client-applicationcostprofiler");
const {
  ApplicationInsights
} = require("@aws-sdk/client-application-insights");
const {
  Athena
} = require("@aws-sdk/client-athena");
const {
  AuditManager
} = require("@aws-sdk/client-auditmanager");
const {
  SageMakerA2IRuntime
} = require("@aws-sdk/client-sage-maker-a2iruntime");
const {
  AutoScaling
} = require("@aws-sdk/client-auto-scaling");
const {
  AutoScalingPlans
} = require("@aws-sdk/client-auto-scaling-plans");
const {
  Backup
} = require("@aws-sdk/client-backup");
const {
  BackupGateway
} = require("@aws-sdk/client-backup-gateway");
const {
  BackupStorage
} = require("@aws-sdk/client-backupstorage");
const {
  Batch
} = require("@aws-sdk/client-batch");
const {
  Billingconductor
} = require("@aws-sdk/client-billingconductor");
const {
  Braket
} = require("@aws-sdk/client-braket");
const {
  Budgets
} = require("@aws-sdk/client-budgets");
const {
  CostAndUsageReportService
} = require("@aws-sdk/client-cost-and-usage-report-service");
const {
  Chime
} = require("@aws-sdk/client-chime");
const {
  ChimeSDKIdentity
} = require("@aws-sdk/client-chime-sdk-identity");
const {
  ChimeSDKMediaPipelines
} = require("@aws-sdk/client-chime-sdk-media-pipelines");
const {
  ChimeSDKMeetings
} = require("@aws-sdk/client-chime-sdk-meetings");
const {
  ChimeSDKMessaging
} = require("@aws-sdk/client-chime-sdk-messaging");
const {
  ChimeSDKVoice
} = require("@aws-sdk/client-chime-sdk-voice");
const {
  Cloud9
} = require("@aws-sdk/client-cloud9");
const {
  CloudControl
} = require("@aws-sdk/client-cloudcontrol");
const {
  CloudDirectory
} = require("@aws-sdk/client-clouddirectory");
const {
  CloudFormation
} = require("@aws-sdk/client-cloudformation");
const {
  CloudFront
} = require("@aws-sdk/client-cloudfront");
const {
  CloudHSM
} = require("@aws-sdk/client-cloudhsm");
const {
  CloudHSMV2
} = require("@aws-sdk/client-cloudhsm-v2");
const {
  CloudSearch
} = require("@aws-sdk/client-cloudsearch");
const {
  CloudSearchDomain
} = require("@aws-sdk/client-cloudsearch-domain");
const {
  CloudTrail
} = require("@aws-sdk/client-cloudtrail");
const {
  CloudWatch
} = require("@aws-sdk/client-cloudwatch");
const {
  CloudWatchEvents
} = require("@aws-sdk/client-cloudwatch-events");
const {
  CloudWatchLogs
} = require("@aws-sdk/client-cloudwatch-logs");
const {
  Codeartifact
} = require("@aws-sdk/client-codeartifact");
const {
  CodeBuild
} = require("@aws-sdk/client-codebuild");
const {
  CodeCatalyst
} = require("@aws-sdk/client-codecatalyst");
const {
  CodeCommit
} = require("@aws-sdk/client-codecommit");
const {
  CodeDeploy
} = require("@aws-sdk/client-codedeploy");
const {
  CodeGuruProfiler
} = require("@aws-sdk/client-codeguruprofiler");
const {
  CodeGuruReviewer
} = require("@aws-sdk/client-codeguru-reviewer");
const {
  CodePipeline
} = require("@aws-sdk/client-codepipeline");
const {
  CodeStar
} = require("@aws-sdk/client-codestar");
const {
  CodestarNotifications
} = require("@aws-sdk/client-codestar-notifications");
const {
  CodeStarConnections
} = require("@aws-sdk/client-codestar-connections");
const {
  CognitoIdentity
} = require("@aws-sdk/client-cognito-identity");
const {
  CognitoIdentityProvider
} = require("@aws-sdk/client-cognito-identity-provider");
const {
  CognitoSync
} = require("@aws-sdk/client-cognito-sync");
const {
  Comprehend
} = require("@aws-sdk/client-comprehend");
const {
  ComprehendMedical
} = require("@aws-sdk/client-comprehendmedical");
const {
  ComputeOptimizer
} = require("@aws-sdk/client-compute-optimizer");
const {
  ConfigService
} = require("@aws-sdk/client-config-service");
const {
  Connect
} = require("@aws-sdk/client-connect");
const {
  ConnectCampaigns
} = require("@aws-sdk/client-connectcampaigns");
const {
  ConnectCases
} = require("@aws-sdk/client-connectcases");
const {
  ConnectContactLens
} = require("@aws-sdk/client-connect-contact-lens");
const {
  ConnectParticipant
} = require("@aws-sdk/client-connectparticipant");
const {
  ControlTower
} = require("@aws-sdk/client-controltower");
const {
  CostExplorer
} = require("@aws-sdk/client-cost-explorer");
const {
  CustomerProfiles
} = require("@aws-sdk/client-customer-profiles");
const {
  DAX
} = require("@aws-sdk/client-dax");
const {
  DLM
} = require("@aws-sdk/client-dlm");
const {
  DatabaseMigrationService
} = require("@aws-sdk/client-database-migration-service");
const {
  DataBrew
} = require("@aws-sdk/client-databrew");
const {
  DataExchange
} = require("@aws-sdk/client-dataexchange");
const {
  DataPipeline
} = require("@aws-sdk/client-data-pipeline");
const {
  DataSync
} = require("@aws-sdk/client-datasync");
const {
  Detective
} = require("@aws-sdk/client-detective");
const {
  DevOpsGuru
} = require("@aws-sdk/client-devops-guru");
const {
  DeviceFarm
} = require("@aws-sdk/client-device-farm");
const {
  DirectConnect
} = require("@aws-sdk/client-direct-connect");
const {
  DirectoryService
} = require("@aws-sdk/client-directory-service");
const {
  ApplicationDiscoveryService
} = require("@aws-sdk/client-application-discovery-service");
const {
  DocDB
} = require("@aws-sdk/client-docdb");
const {
  DocDBElastic
} = require("@aws-sdk/client-docdb-elastic");
const {
  Drs
} = require("@aws-sdk/client-drs");
const {
  DynamoDB
} = require("@aws-sdk/client-dynamodb");
const {
  DynamoDBStreams
} = require("@aws-sdk/client-dynamodb-streams");
const {
  EBS
} = require("@aws-sdk/client-ebs");
const {
  EC2
} = require("@aws-sdk/client-ec2");
const {
  EC2InstanceConnect
} = require("@aws-sdk/client-ec2-instance-connect");
const {
  ECR
} = require("@aws-sdk/client-ecr");
const {
  ECRPUBLIC
} = require("@aws-sdk/client-ecr-public");
const {
  ECS
} = require("@aws-sdk/client-ecs");
const {
  EFS
} = require("@aws-sdk/client-efs");
const {
  EKS
} = require("@aws-sdk/client-eks");
const {
  ElasticLoadBalancing
} = require("@aws-sdk/client-elastic-load-balancing");
const {
  ElasticLoadBalancingV2
} = require("@aws-sdk/client-elastic-load-balancing-v2");
const {
  EMR
} = require("@aws-sdk/client-emr");
const {
  EMRServerless
} = require("@aws-sdk/client-emr-serverless");
const {
  EMRContainers
} = require("@aws-sdk/client-emr-containers");
const {
  ElasticsearchService
} = require("@aws-sdk/client-elasticsearch-service");
const {
  ElastiCache
} = require("@aws-sdk/client-elasticache");
const {
  ElasticBeanstalk
} = require("@aws-sdk/client-elastic-beanstalk");
const {
  ElasticInference
} = require("@aws-sdk/client-elastic-inference");
const {
  ElasticTranscoder
} = require("@aws-sdk/client-elastic-transcoder");
const {
  EventBridge
} = require("@aws-sdk/client-eventbridge");
const {
  Evidently
} = require("@aws-sdk/client-evidently");
const {
  FMS
} = require("@aws-sdk/client-fms");
const {
  FSx
} = require("@aws-sdk/client-fsx");
const {
  Finspace
} = require("@aws-sdk/client-finspace");
const {
  FinspaceData
} = require("@aws-sdk/client-finspace-data");
const {
  Firehose
} = require("@aws-sdk/client-firehose");
const {
  Fis
} = require("@aws-sdk/client-fis");
const {
  Forecastquery
} = require("@aws-sdk/client-forecastquery");
const {
  Forecast
} = require("@aws-sdk/client-forecast");
const {
  FraudDetector
} = require("@aws-sdk/client-frauddetector");
const {
  GameLift
} = require("@aws-sdk/client-gamelift");
const {
  GameSparks
} = require("@aws-sdk/client-gamesparks");
const {
  Glacier
} = require("@aws-sdk/client-glacier");
const {
  GlobalAccelerator
} = require("@aws-sdk/client-global-accelerator");
const {
  Glue
} = require("@aws-sdk/client-glue");
const {
  Grafana
} = require("@aws-sdk/client-grafana");
const {
  Greengrass
} = require("@aws-sdk/client-greengrass");
const {
  GreengrassV2
} = require("@aws-sdk/client-greengrassv2");
const {
  GroundStation
} = require("@aws-sdk/client-groundstation");
const {
  GuardDuty
} = require("@aws-sdk/client-guardduty");
const {
  Health
} = require("@aws-sdk/client-health");
const {
  HealthLake
} = require("@aws-sdk/client-healthlake");
const {
  Honeycode
} = require("@aws-sdk/client-honeycode");
const {
  IAM
} = require("@aws-sdk/client-iam");
const {
  Ivs
} = require("@aws-sdk/client-ivs");
const {
  Identitystore
} = require("@aws-sdk/client-identitystore");
const {
  Imagebuilder
} = require("@aws-sdk/client-imagebuilder");
const {
  Inspector
} = require("@aws-sdk/client-inspector");
const {
  Inspector2
} = require("@aws-sdk/client-inspector2");
const {
  IoT1ClickDevicesService
} = require("@aws-sdk/client-iot-1click-devices-service");
const {
  IoT1ClickProjects
} = require("@aws-sdk/client-iot-1click-projects");
const {
  IoTAnalytics
} = require("@aws-sdk/client-iotanalytics");
const {
  IoTEvents
} = require("@aws-sdk/client-iot-events");
const {
  IoTEventsData
} = require("@aws-sdk/client-iot-events-data");
const {
  IoTFleetHub
} = require("@aws-sdk/client-iotfleethub");
const {
  IoTFleetWise
} = require("@aws-sdk/client-iotfleetwise");
const {
  IoTJobsDataPlane
} = require("@aws-sdk/client-iot-jobs-data-plane");
const {
  IoTRoboRunner
} = require("@aws-sdk/client-iot-roborunner");
const {
  IoTSecureTunneling
} = require("@aws-sdk/client-iotsecuretunneling");
const {
  IoTSiteWise
} = require("@aws-sdk/client-iotsitewise");
const {
  IoTThingsGraph
} = require("@aws-sdk/client-iotthingsgraph");
const {
  IoTTwinMaker
} = require("@aws-sdk/client-iottwinmaker");
const {
  IoTWireless
} = require("@aws-sdk/client-iot-wireless");
const {
  IoT
} = require("@aws-sdk/client-iot");
const {
  IoTDataPlane
} = require("@aws-sdk/client-iot-data-plane");
const {
  IotDeviceAdvisor
} = require("@aws-sdk/client-iotdeviceadvisor");
const {
  Ivschat
} = require("@aws-sdk/client-ivschat");
const {
  KMS
} = require("@aws-sdk/client-kms");
const {
  Kafka
} = require("@aws-sdk/client-kafka");
const {
  KafkaConnect
} = require("@aws-sdk/client-kafkaconnect");
const {
  Kendra
} = require("@aws-sdk/client-kendra");
const {
  Keyspaces
} = require("@aws-sdk/client-keyspaces");
const {
  Kinesis
} = require("@aws-sdk/client-kinesis");
const {
  KinesisAnalytics
} = require("@aws-sdk/client-kinesis-analytics");
const {
  KinesisAnalyticsV2
} = require("@aws-sdk/client-kinesis-analytics-v2");
const {
  KinesisVideo
} = require("@aws-sdk/client-kinesis-video");
const {
  KinesisVideoArchivedMedia
} = require("@aws-sdk/client-kinesis-video-archived-media");
const {
  KinesisVideoMedia
} = require("@aws-sdk/client-kinesis-video-media");
const {
  KinesisVideoSignaling
} = require("@aws-sdk/client-kinesis-video-signaling");
const {
  KinesisVideoWebRTCStorage
} = require("@aws-sdk/client-kinesis-video-webrtc-storage");
const {
  LakeFormation
} = require("@aws-sdk/client-lakeformation");
const {
  Lambda
} = require("@aws-sdk/client-lambda");
const {
  LexModelBuildingService
} = require("@aws-sdk/client-lex-model-building-service");
const {
  LexModelsV2
} = require("@aws-sdk/client-lex-models-v2");
const {
  LexRuntimeService
} = require("@aws-sdk/client-lex-runtime-service");
const {
  LexRuntimeV2
} = require("@aws-sdk/client-lex-runtime-v2");
const {
  LicenseManager
} = require("@aws-sdk/client-license-manager");
const {
  LicenseManagerLinuxSubscriptions
} = require("@aws-sdk/client-license-manager-linux-subscriptions");
const {
  LicenseManagerUserSubscriptions
} = require("@aws-sdk/client-license-manager-user-subscriptions");
const {
  Lightsail
} = require("@aws-sdk/client-lightsail");
const {
  Location
} = require("@aws-sdk/client-location");
const {
  LookoutEquipment
} = require("@aws-sdk/client-lookoutequipment");
const {
  LookoutMetrics
} = require("@aws-sdk/client-lookoutmetrics");
const {
  LookoutVision
} = require("@aws-sdk/client-lookoutvision");
const {
  M2
} = require("@aws-sdk/client-m2");
const {
  Mq
} = require("@aws-sdk/client-mq");
const {
  MTurk
} = require("@aws-sdk/client-mturk");
const {
  MWAA
} = require("@aws-sdk/client-mwaa");
const {
  MachineLearning
} = require("@aws-sdk/client-machine-learning");
const {
  Macie
} = require("@aws-sdk/client-macie");
const {
  Macie2
} = require("@aws-sdk/client-macie2");
const {
  ManagedBlockchain
} = require("@aws-sdk/client-managedblockchain");
const {
  MarketplaceCatalog
} = require("@aws-sdk/client-marketplace-catalog");
const {
  MarketplaceCommerceAnalytics
} = require("@aws-sdk/client-marketplace-commerce-analytics");
const {
  MarketplaceEntitlementService
} = require("@aws-sdk/client-marketplace-entitlement-service");
const {
  MarketplaceMetering
} = require("@aws-sdk/client-marketplace-metering");
const {
  MediaConnect
} = require("@aws-sdk/client-mediaconnect");
const {
  MediaConvert
} = require("@aws-sdk/client-mediaconvert");
const {
  MediaLive
} = require("@aws-sdk/client-medialive");
const {
  MediaPackage
} = require("@aws-sdk/client-mediapackage");
const {
  MediaPackageVod
} = require("@aws-sdk/client-mediapackage-vod");
const {
  MediaStore
} = require("@aws-sdk/client-mediastore");
const {
  MediaStoreData
} = require("@aws-sdk/client-mediastore-data");
const {
  MediaTailor
} = require("@aws-sdk/client-mediatailor");
const {
  MemoryDB
} = require("@aws-sdk/client-memory-db");
const {
  Mgn
} = require("@aws-sdk/client-mgn");
const {
  MigrationHub
} = require("@aws-sdk/client-migration-hub");
const {
  MigrationHubConfig
} = require("@aws-sdk/client-migrationhub-config");
const {
  MigrationHubOrchestrator
} = require("@aws-sdk/client-migrationhuborchestrator");
const {
  MigrationHubRefactorSpaces
} = require("@aws-sdk/client-migration-hub-refactor-spaces");
const {
  MigrationHubStrategy
} = require("@aws-sdk/client-migrationhubstrategy");
const {
  Mobile
} = require("@aws-sdk/client-mobile");
const {
  Neptune
} = require("@aws-sdk/client-neptune");
const {
  NetworkFirewall
} = require("@aws-sdk/client-network-firewall");
const {
  NetworkManager
} = require("@aws-sdk/client-networkmanager");
const {
  Nimble
} = require("@aws-sdk/client-nimble");
const {
  OAM
} = require("@aws-sdk/client-oam");
const {
  Omics
} = require("@aws-sdk/client-omics");
const {
  OpenSearch
} = require("@aws-sdk/client-opensearch");
const {
  OpenSearchServerless
} = require("@aws-sdk/client-opensearchserverless");
const {
  OpsWorks
} = require("@aws-sdk/client-opsworks");
const {
  OpsWorksCM
} = require("@aws-sdk/client-opsworkscm");
const {
  Organizations
} = require("@aws-sdk/client-organizations");
const {
  Outposts
} = require("@aws-sdk/client-outposts");
const {
  PI
} = require("@aws-sdk/client-pi");
const {
  Panorama
} = require("@aws-sdk/client-panorama");
const {
  Personalize
} = require("@aws-sdk/client-personalize");
const {
  PersonalizeEvents
} = require("@aws-sdk/client-personalize-events");
const {
  PersonalizeRuntime
} = require("@aws-sdk/client-personalize-runtime");
const {
  Pinpoint
} = require("@aws-sdk/client-pinpoint");
const {
  PinpointEmail
} = require("@aws-sdk/client-pinpoint-email");
const {
  PinpointSMSVoice
} = require("@aws-sdk/client-pinpoint-sms-voice");
const {
  PinpointSMSVoiceV2
} = require("@aws-sdk/client-pinpoint-sms-voice-v2");
const {
  Pipes
} = require("@aws-sdk/client-pipes");
const {
  Polly
} = require("@aws-sdk/client-polly");
const {
  Pricing
} = require("@aws-sdk/client-pricing");
const {
  PrivateNetworks
} = require("@aws-sdk/client-privatenetworks");
const {
  Proton
} = require("@aws-sdk/client-proton");
const {
  QLDB
} = require("@aws-sdk/client-qldb");
const {
  QLDBSession
} = require("@aws-sdk/client-qldb-session");
const {
  QuickSight
} = require("@aws-sdk/client-quicksight");
const {
  RAM
} = require("@aws-sdk/client-ram");
const {
  RDS
} = require("@aws-sdk/client-rds");
const {
  RDSData
} = require("@aws-sdk/client-rds-data");
const {
  RUM
} = require("@aws-sdk/client-rum");
const {
  Rbin
} = require("@aws-sdk/client-rbin");
const {
  Redshift
} = require("@aws-sdk/client-redshift");
const {
  RedshiftData
} = require("@aws-sdk/client-redshift-data");
const {
  RedshiftServerless
} = require("@aws-sdk/client-redshift-serverless");
const {
  Rekognition
} = require("@aws-sdk/client-rekognition");
const {
  Resiliencehub
} = require("@aws-sdk/client-resiliencehub");
const {
  ResourceExplorer2
} = require("@aws-sdk/client-resource-explorer-2");
const {
  ResourceGroups
} = require("@aws-sdk/client-resource-groups");
const {
  ResourceGroupsTaggingAPI
} = require("@aws-sdk/client-resource-groups-tagging-api");
const {
  RoboMaker
} = require("@aws-sdk/client-robomaker");
const {
  RolesAnywhere
} = require("@aws-sdk/client-rolesanywhere");
const {
  Route53
} = require("@aws-sdk/client-route-53");
const {
  Route53Domains
} = require("@aws-sdk/client-route-53-domains");
const {
  Route53RecoveryCluster
} = require("@aws-sdk/client-route53-recovery-cluster");
const {
  Route53RecoveryControlConfig
} = require("@aws-sdk/client-route53-recovery-control-config");
const {
  Route53RecoveryReadiness
} = require("@aws-sdk/client-route53-recovery-readiness");
const {
  Route53Resolver
} = require("@aws-sdk/client-route53resolver");
const {
  S3
} = require("@aws-sdk/client-s3");
const {
  S3Control
} = require("@aws-sdk/client-s3-control");
const {
  S3Outposts
} = require("@aws-sdk/client-s3outposts");
const {
  SES
} = require("@aws-sdk/client-ses");
const {
  SESv2
} = require("@aws-sdk/client-sesv2");
const {
  SMS
} = require("@aws-sdk/client-sms");
const {
  SNS
} = require("@aws-sdk/client-sns");
const {
  SQS
} = require("@aws-sdk/client-sqs");
const {
  SSM
} = require("@aws-sdk/client-ssm");
const {
  SSMContacts
} = require("@aws-sdk/client-ssm-contacts");
const {
  SSMIncidents
} = require("@aws-sdk/client-ssm-incidents");
const {
  SSO
} = require("@aws-sdk/client-sso");
const {
  SSOAdmin
} = require("@aws-sdk/client-sso-admin");
const {
  SSOOIDC
} = require("@aws-sdk/client-sso-oidc");
const {
  STS
} = require("@aws-sdk/client-sts");
const {
  SWF
} = require("@aws-sdk/client-swf");
const {
  SageMaker
} = require("@aws-sdk/client-sagemaker");
const {
  SageMakerFeatureStoreRuntime
} = require("@aws-sdk/client-sagemaker-featurestore-runtime");
const {
  SageMakerGeospatial
} = require("@aws-sdk/client-sagemaker-geospatial");
const {
  SageMakerMetrics
} = require("@aws-sdk/client-sagemaker-metrics");
const {
  SageMakerRuntime
} = require("@aws-sdk/client-sagemaker-runtime");
const {
  SagemakerEdge
} = require("@aws-sdk/client-sagemaker-edge");
const {
  Savingsplans
} = require("@aws-sdk/client-savingsplans");
const {
  Scheduler
} = require("@aws-sdk/client-scheduler");
const {
  Schemas
} = require("@aws-sdk/client-schemas");
const {
  SecretsManager
} = require("@aws-sdk/client-secrets-manager");
const {
  SecurityHub
} = require("@aws-sdk/client-securityhub");
const {
  SecurityLake
} = require("@aws-sdk/client-securitylake");
const {
  ServerlessApplicationRepository
} = require("@aws-sdk/client-serverlessapplicationrepository");
const {
  ServiceCatalog
} = require("@aws-sdk/client-service-catalog");
const {
  ServiceCatalogAppRegistry
} = require("@aws-sdk/client-service-catalog-appregistry");
const {
  ServiceDiscovery
} = require("@aws-sdk/client-servicediscovery");
const {
  ServiceQuotas
} = require("@aws-sdk/client-service-quotas");
const {
  Shield
} = require("@aws-sdk/client-shield");
const {
  Signer
} = require("@aws-sdk/client-signer");
const {
  SimSpaceWeaver
} = require("@aws-sdk/client-simspaceweaver");
const {
  SnowDeviceManagement
} = require("@aws-sdk/client-snow-device-management");
const {
  Snowball
} = require("@aws-sdk/client-snowball");
const {
  SsmSap
} = require("@aws-sdk/client-ssm-sap");
const {
  SFN
} = require("@aws-sdk/client-sfn");
const {
  StorageGateway
} = require("@aws-sdk/client-storage-gateway");
const {
  Support
} = require("@aws-sdk/client-support");
const {
  SupportApp
} = require("@aws-sdk/client-support-app");
const {
  Synthetics
} = require("@aws-sdk/client-synthetics");
const {
  Textract
} = require("@aws-sdk/client-textract");
const {
  TimestreamQuery
} = require("@aws-sdk/client-timestream-query");
const {
  TimestreamWrite
} = require("@aws-sdk/client-timestream-write");
const {
  Transcribe
} = require("@aws-sdk/client-transcribe");
const {
  Transfer
} = require("@aws-sdk/client-transfer");
const {
  Translate
} = require("@aws-sdk/client-translate");
const {
  VoiceID
} = require("@aws-sdk/client-voice-id");
const {
  WAF
} = require("@aws-sdk/client-waf");
const {
  WAFRegional
} = require("@aws-sdk/client-waf-regional");
const {
  WAFV2
} = require("@aws-sdk/client-wafv2");
const {
  WellArchitected
} = require("@aws-sdk/client-wellarchitected");
const {
  Wisdom
} = require("@aws-sdk/client-wisdom");
const {
  WorkDocs
} = require("@aws-sdk/client-workdocs");
const {
  WorkLink
} = require("@aws-sdk/client-worklink");
const {
  WorkMail
} = require("@aws-sdk/client-workmail");
const {
  WorkMailMessageFlow
} = require("@aws-sdk/client-workmailmessageflow");
const {
  WorkSpaces
} = require("@aws-sdk/client-workspaces");
const {
  WorkSpacesWeb
} = require("@aws-sdk/client-workspaces-web");
const {
  XRay
} = require("@aws-sdk/client-xray");

new ACM();
new ACMPCA();
new APIGateway();
new ARCZonalShift();
new AccessAnalyzer();
new Account();
new AlexaForBusiness();
new Amp();
new Amplify();
new AmplifyBackend();
new AmplifyUIBuilder();
new ApiGatewayManagementApi();
new ApiGatewayV2();
new AppConfig();
new AppConfigData();
new AppIntegrations();
new AppMesh();
new AppRunner();
new AppStream();
new AppSync();
new Appflow();
new ApplicationAutoScaling();
new ApplicationCostProfiler();
new ApplicationInsights();
new Athena();
new AuditManager();
new SageMakerA2IRuntime();
new AutoScaling();
new AutoScalingPlans();
new Backup();
new BackupGateway();
new BackupStorage();
new Batch();
new Billingconductor();
new Braket();
new Budgets();
new CostAndUsageReportService();
new Chime();
new ChimeSDKIdentity();
new ChimeSDKMediaPipelines();
new ChimeSDKMeetings();
new ChimeSDKMessaging();
new ChimeSDKVoice();
new Cloud9();
new CloudControl();
new CloudDirectory();
new CloudFormation();
new CloudFront();
new CloudHSM();
new CloudHSMV2();
new CloudSearch();
new CloudSearchDomain();
new CloudTrail();
new CloudWatch();
new CloudWatchEvents();
new CloudWatchLogs();
new Codeartifact();
new CodeBuild();
new CodeCatalyst();
new CodeCommit();
new CodeDeploy();
new CodeGuruProfiler();
new CodeGuruReviewer();
new CodePipeline();
new CodeStar();
new CodestarNotifications();
new CodeStarConnections();
new CognitoIdentity();
new CognitoIdentityProvider();
new CognitoSync();
new Comprehend();
new ComprehendMedical();
new ComputeOptimizer();
new ConfigService();
new Connect();
new ConnectCampaigns();
new ConnectCases();
new ConnectContactLens();
new ConnectParticipant();
new ControlTower();
new CostExplorer();
new CustomerProfiles();
new DAX();
new DLM();
new DatabaseMigrationService();
new DataBrew();
new DataExchange();
new DataPipeline();
new DataSync();
new Detective();
new DevOpsGuru();
new DeviceFarm();
new DirectConnect();
new DirectoryService();
new ApplicationDiscoveryService();
new DocDB();
new DocDBElastic();
new Drs();
new DynamoDB();
new DynamoDBStreams();
new EBS();
new EC2();
new EC2InstanceConnect();
new ECR();
new ECRPUBLIC();
new ECS();
new EFS();
new EKS();
new ElasticLoadBalancing();
new ElasticLoadBalancingV2();
new EMR();
new EMRServerless();
new EMRContainers();
new ElasticsearchService();
new ElastiCache();
new ElasticBeanstalk();
new ElasticInference();
new ElasticTranscoder();
new EventBridge();
new Evidently();
new FMS();
new FSx();
new Finspace();
new FinspaceData();
new Firehose();
new Fis();
new Forecastquery();
new Forecast();
new FraudDetector();
new GameLift();
new GameSparks();
new Glacier();
new GlobalAccelerator();
new Glue();
new Grafana();
new Greengrass();
new GreengrassV2();
new GroundStation();
new GuardDuty();
new Health();
new HealthLake();
new Honeycode();
new IAM();
new Ivs();
new Identitystore();
new Imagebuilder();
new Inspector();
new Inspector2();
new IoT1ClickDevicesService();
new IoT1ClickProjects();
new IoTAnalytics();
new IoTEvents();
new IoTEventsData();
new IoTFleetHub();
new IoTFleetWise();
new IoTJobsDataPlane();
new IoTRoboRunner();
new IoTSecureTunneling();
new IoTSiteWise();
new IoTThingsGraph();
new IoTTwinMaker();
new IoTWireless();
new IoT();
new IoTDataPlane();
new IotDeviceAdvisor();
new Ivschat();
new KMS();
new Kafka();
new KafkaConnect();
new Kendra();
new Keyspaces();
new Kinesis();
new KinesisAnalytics();
new KinesisAnalyticsV2();
new KinesisVideo();
new KinesisVideoArchivedMedia();
new KinesisVideoMedia();
new KinesisVideoSignaling();
new KinesisVideoWebRTCStorage();
new LakeFormation();
new Lambda();
new LexModelBuildingService();
new LexModelsV2();
new LexRuntimeService();
new LexRuntimeV2();
new LicenseManager();
new LicenseManagerLinuxSubscriptions();
new LicenseManagerUserSubscriptions();
new Lightsail();
new Location();
new LookoutEquipment();
new LookoutMetrics();
new LookoutVision();
new M2();
new Mq();
new MTurk();
new MWAA();
new MachineLearning();
new Macie();
new Macie2();
new ManagedBlockchain();
new MarketplaceCatalog();
new MarketplaceCommerceAnalytics();
new MarketplaceEntitlementService();
new MarketplaceMetering();
new MediaConnect();
new MediaConvert();
new MediaLive();
new MediaPackage();
new MediaPackageVod();
new MediaStore();
new MediaStoreData();
new MediaTailor();
new MemoryDB();
new Mgn();
new MigrationHub();
new MigrationHubConfig();
new MigrationHubOrchestrator();
new MigrationHubRefactorSpaces();
new MigrationHubStrategy();
new Mobile();
new Neptune();
new NetworkFirewall();
new NetworkManager();
new Nimble();
new OAM();
new Omics();
new OpenSearch();
new OpenSearchServerless();
new OpsWorks();
new OpsWorksCM();
new Organizations();
new Outposts();
new PI();
new Panorama();
new Personalize();
new PersonalizeEvents();
new PersonalizeRuntime();
new Pinpoint();
new PinpointEmail();
new PinpointSMSVoice();
new PinpointSMSVoiceV2();
new Pipes();
new Polly();
new Pricing();
new PrivateNetworks();
new Proton();
new QLDB();
new QLDBSession();
new QuickSight();
new RAM();
new RDS();
new RDSData();
new RUM();
new Rbin();
new Redshift();
new RedshiftData();
new RedshiftServerless();
new Rekognition();
new Resiliencehub();
new ResourceExplorer2();
new ResourceGroups();
new ResourceGroupsTaggingAPI();
new RoboMaker();
new RolesAnywhere();
new Route53();
new Route53Domains();
new Route53RecoveryCluster();
new Route53RecoveryControlConfig();
new Route53RecoveryReadiness();
new Route53Resolver();
new S3();
new S3Control();
new S3Outposts();
new SES();
new SESv2();
new SMS();
new SNS();
new SQS();
new SSM();
new SSMContacts();
new SSMIncidents();
new SSO();
new SSOAdmin();
new SSOOIDC();
new STS();
new SWF();
new SageMaker();
new SageMakerFeatureStoreRuntime();
new SageMakerGeospatial();
new SageMakerMetrics();
new SageMakerRuntime();
new SagemakerEdge();
new Savingsplans();
new Scheduler();
new Schemas();
new SecretsManager();
new SecurityHub();
new SecurityLake();
new ServerlessApplicationRepository();
new ServiceCatalog();
new ServiceCatalogAppRegistry();
new ServiceDiscovery();
new ServiceQuotas();
new Shield();
new Signer();
new SimSpaceWeaver();
new SnowDeviceManagement();
new Snowball();
new SsmSap();
new SFN();
new StorageGateway();
new Support();
new SupportApp();
new Synthetics();
new Textract();
new TimestreamQuery();
new TimestreamWrite();
new Transcribe();
new Transfer();
new Translate();
new VoiceID();
new WAF();
new WAFRegional();
new WAFV2();
new WellArchitected();
new Wisdom();
new WorkDocs();
new WorkLink();
new WorkMail();
new WorkMailMessageFlow();
new WorkSpaces();
new WorkSpacesWeb();
new XRay();
