// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
const {
        AccessAnalyzer
      } = require("@aws-sdk/client-accessanalyzer"),
      {
        ACM
      } = require("@aws-sdk/client-acm"),
      {
        ApplicationDiscoveryService: Discovery
      } = require("@aws-sdk/client-application-discovery-service");

new ACM();
new AccessAnalyzer();
new Discovery();
