// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
import * as ACM from "aws-sdk/clients/acm";
import * as AccessAnalyzer from "aws-sdk/clients/accessanalyzer";
import * as Discovery from "aws-sdk/clients/discovery";

new ACM();
new AccessAnalyzer();
new Discovery();
