// This file is generated by scripts/generateNewClientTests/index.ts
// Do not edit this file directly. Instead, edit the script and run it to regenerate this file.
"use strict";
const { 
  ACM: ACMClient,
  AccessAnalyzer: AccessAnalyzerClient,
  Discovery: DiscoveryClient
 } = require("aws-sdk");

new ACMClient();
new AccessAnalyzerClient();
new DiscoveryClient();
